services:
  loadbalancer-ipfs:
    container_name: loadbalancer-ipfs
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - /root/loadbalance-ipfs:/etc/nginx/conf.d
      - /root/ssl:/etc/nginx/ssl
      - /root/.htpasswd:/etc/nginx/.htpasswd

